import { useQuery } from "@tanstack/react-query";
import { spWebContext } from "api/SPWebContext";

export const useProgramGroups = () => {
  return useQuery({
    queryKey: ["ProgramGroups"],
    queryFn: getProgramGroups,
    staleTime: Infinity,
    cacheTime: Infinity,
  });
};

const getProgramGroups = () => {
  if (!import.meta.env.DEV) {
    return spWebContext.web.lists
      .getByTitle("ProgramGroups")
      .items.orderBy("Title")
      .top(5000)();
  } else {
    return [
      { Title: "330 TACTICAL AIRLIFT CSG", Id: 1 },
      { Title: "542 ELECTRONIC WARFARE CSG", Id: 2 },
      { Title: "642 SUPT EQMT & VEHICLES CSG", Id: 3 },
      { Title: "730 STRATEGIC AIRLIFT CSG", Id: 4 },
      { Title: "830 FIGHTER CSG", Id: 5 },
      { Title: "A010", Id: 6 },
      { Title: "ADVANCED PILOT TRAINING", Id: 7 },
      { Title: "AERIAL TARGETS", Id: 8 },
      { Title: "AERONAUTICAL MISSILES AND WEAPONS", Id: 9 },
      { Title: "AEWS", Id: 10 },
      { Title: "AF CYBER DEFENSE", Id: 11 },
      { Title: "AF CYBER OPERATIONS", Id: 12 },
      { Title: "AFMETCAL", Id: 13 },
      { Title: "AFSOC (C130J) ", Id: 14 },
      { Title: "AFWS-ALC", Id: 15 },
      { Title: "AFWS-SMC", Id: 16 },
      { Title: "AGILE COMBAT SUPPORT", Id: 17 },
      { Title: "AIR DOMINANCE", Id: 18 },
      { Title: "AIR FORCE MEDICAL SERVICE", Id: 19 },
      { Title: "AIR FORCE WEATHER WEAPON SYSTEMS", Id: 20 },
      { Title: "AIR MOBILITY TACTICAL DATA SYSTEMS", Id: 21 },
      { Title: "AIR TRAFFIC CONTROL AND LANDING SYSTEMS", Id: 22 },
      { Title: "AIRCRAFT MOBILITY DIRECTORATE", Id: 23 },
      { Title: "AN/FPS", Id: 24 },
      { Title: "ANG (C130)", Id: 25 },
      { Title: "ARMAMENT SUSTAINMENT", Id: 26 },
      { Title: "ATCALS", Id: 27 },
      { Title: "AUTOMATIC TEST SYSTEMS", Id: 28 },
      { Title: "AgilePod", Id: 29 },
      { Title: "BA 01", Id: 30 },
      { Title: "B001", Id: 31 },
      { Title: "B002", Id: 32 },
      { Title: "B021", Id: 33 },
      { Title: "B052", Id: 34 },
      { Title: "BALLISTIC MISSILE EARLY WARNING SYSTEM", Id: 35 },
      { Title: "BASE IT INFRASTRUCTURE", Id: 36 },
      { Title: "BATTLE MANAGEMENT SYSTEMS", Id: 37 },
      { Title: "C/KC - 135 (KC-135)", Id: 38 },
      { Title: "C/KC - 135 (OC-135)", Id: 39 },
      { Title: "C005", Id: 40 },
      { Title: "C017", Id: 41 },
      { Title: "C130", Id: 42 },
      { Title: "C130 (C130J)", Id: 43 },
      { Title: "C145", Id: 44 },
      { Title: "C146", Id: 45 },
      { Title: "CHEMICAL", Id: 46 },
      { Title: "CLS", Id: 47 },
      { Title: "CLS AIRCRAFT (C012)", Id: 48 },
      { Title: "CLS AIRCRAFT (C020)", Id: 49 },
      { Title: "CLS AIRCRAFT (C021)", Id: 50 },
      { Title: "CLS AIRCRAFT (C026)", Id: 51 },
      { Title: "CLS AIRCRAFT (C038)", Id: 52 },
      { Title: "CLS AIRCRAFT (E004)", Id: 53 },
      { Title: "CLS AIRCRAFT (E009A)", Id: 54 },
      { Title: "CLS AIRCRAFT (KC010)", Id: 55 },
      { Title: "CLS AIRCRAFT (T001A)", Id: 56 },
      { Title: "CLS AIRCRAFT (VC025)", Id: 57 },
      { Title: "CLS TRAINER", Id: 58 },
      { Title: "CLS USAFA", Id: 59 },
      { Title: "CLS VIP SAM", Id: 60 },
      { Title: "COMBAT INFORMATION TRANSPORT SYSTEM", Id: 61 },
      { Title: "COMMON ALC", Id: 62 },
      { Title: "COMMON AVIONICS AND ELECTRONIC SYSTEMS", Id: 63 },
      { Title: "COMMON NWC", Id: 64 },
      { Title: "COMSEC Systems", Id: 65 },
      {
        Title:
          "Consolidated Sustainment Activity Group (CSAG) - Supply Division - Robins",
        Id: 66,
      },
      { Title: "COUNTERSPACE OPS", Id: 67 },
      { Title: "CRC", Id: 68 },
      { Title: "CRUISE MISSILE GROUP", Id: 69 },
      { Title: "CSAG-S HILL", Id: 70 },
      { Title: "CSAG-S ROBINS", Id: 71 },
      { Title: "CSAG-S TINKER", Id: 72 },
      { Title: "CSEL", Id: 73 },
      { Title: "CV22", Id: 74 },
      { Title: "CV022", Id: 75 },
      { Title: "CYBERSPACE", Id: 76 },
      { Title: "DEFENSE METEOROLOGICAL SATELLITE PROGRAM", Id: 77 },
      { Title: "DEPLOYABLE C3", Id: 78 },
      { Title: "DISTRIBUTED COMMON GROUND SYSTEMS", Id: 79 },
      { Title: "DYNAMIC RETASKING GROUP", Id: 80 },
      { Title: "E003 AIRBORNE WARNING & CONTROL SYSTEM", Id: 81 },
      { Title: "EOD", Id: 82 },
      { Title: "F015C/D", Id: 83 },
      { Title: "F015E", Id: 84 },
      { Title: "F015EX", Id: 85 },
      { Title: "F016", Id: 86 },
      { Title: "F022", Id: 87 },
      { Title: "F035", Id: 88 },
      { Title: "FORCE PROTECTION", Id: 89 },
      { Title: "GLOBAL HAWK", Id: 90 },
      { Title: "H001", Id: 91 },
      { Title: "HC-130-King", Id: 92 },
      { Title: "HH60", Id: 93 },
      { Title: "HIGH FREQUENCY GLOBAL COMMUNICATIONS SYSTEMS", Id: 94 },
      { Title: "HNC-CR", Id: 95 },
      { Title: "HNC-CY", Id: 96 },
      { Title: "HNC-PS", Id: 97 },
      { Title: "HUMAN SYSTEMS", Id: 98 },
      { Title: "IBS", Id: 99 },
      { Title: "ICBM", Id: 100 },
      { Title: "JOINT STARS", Id: 101 },
      { Title: "KC46 TANKER SQUADRONS", Id: 102 },
      { Title: "LAUNCH AND TEST RANGE SYSTEM", Id: 103 },
      { Title: "LIGHT ATTACK AIRCRAFT (LAA) A-29", Id: 104 },
      { Title: "LIGHT ATTACK AIRCRAFT (LAA) AT-6", Id: 105 },
      { Title: "LINK 16 SUPPORT AND SUSTAINMENT", Id: 106 },
      { Title: "LONG RANGE STAND-OFF", Id: 107 },
      { Title: "LONG RANGE SYSTEMS ", Id: 108 },
      { Title: "MH139", Id: 109 },
      { Title: "MILITARY SATELLITE COMMUNICATION", Id: 110 },
      { Title: "MILSATCom-MMP", Id: 111 },
      { Title: "MQ", Id: 112 },
      { Title: "MW/MD Ground Based Radars", Id: 113 },
      { Title: "NAVSTAR GPS", Id: 114 },
      { Title: "NC3", Id: 115 },
      { Title: "NCMC-ITW/AA", Id: 116 },
      { Title: "PHYSIOLOGICAL TRAINERS", Id: 117 },
      { Title: "PROPULSION (AIRCRAFT GAS TURBINE ENGINES)", Id: 118 },
      { Title: "PROVEN AIRCRAFT", Id: 119 },
      { Title: "RANGE THREAT SYSTEMS", Id: 120 },
      { Title: "RECONNAISSANCE EC130H", Id: 121 },
      { Title: "RSLP", Id: 122 },
      { Title: "SECURITY ASSISTANCE TECHNICAL ORDER PROGRAM", Id: 123 },
      { Title: "SLBM RADAR WARNING SYSTEMS", Id: 124 },
      { Title: "SOF (C130)", Id: 125 },
      { Title: "SPACE BASED INFRARED SYSTEMS PROGRAMS", Id: 126 },
      { Title: "SPACE FENCE SURVEILLANCE SYSTEM", Id: 127 },
      { Title: "SPACE INNOVATION AND DEVLOPMENT CENTER", Id: 128 },
      { Title: "SPACE SITUATION AWARENESS OPERATIONS", Id: 129 },
      { Title: "SUPPORT EQUIPMENT AND VEHICLES", Id: 130 },
      { Title: "T038", Id: 131 },
      { Title: "TACP", Id: 132 },
      { Title: "TACTICAL SHELTER SYSTEMS RADOMES AND TOWERS", Id: 133 },
      { Title: "TDN", Id: 134 },
      { Title: "TELECOMMUNICATIONS", Id: 135 },
      { Title: "TEST AND TRAINING SYSTEMS", Id: 136 },
      { Title: "TRAINING SYSTEMS", Id: 137 },
      { Title: "U002", Id: 138 },
      { Title: "UH01", Id: 139 },
      { Title: "VC-025B CDA", Id: 140 },
    ];
  }
};
